### ISSUE TITLE
"RecursionError: maximum recursion depth exceeded while calling a Python object"

### ISSUE THREAD

**Issue by jflot** [nadegeguiglielmoni/GraphUnzip#14]
I tried GraphUnzip to resolve a SPAdes-produced GFA of a 250 Mb genome. A first resolution step using long reads worked fine, but when tried using Hi-C to resolve the graph further I ran into a recursion error:

$ graphunzip.py -g SPAdes_GraphUnzip_10kb.gfa -i matrix -o SPAdes_GraphUnzip_10kb_HiC.gfa unzip

Loading the GFA file
Loading contigs
Loading links
Loading the Hi-C interaction matrix
Everything loaded, moving on to untangling the graph
Merged adjacent contigs for the first time
Traceback (most recent call last):
  File "/Users/jff/.local/bin/graphunzip.py", line 335, in <module>
    main()
  File "/Users/jff/.local/bin/graphunzip.py", line 317, in main
    segments, cn = solve_ambiguities(segments, interactionMatrix, tagInteractionMatrix, multiplicities, names, stringenceReject, stringenceAccept, steps, copiesNumber = cn, debugDir = dbgDir, verbose = verbose)
  File "/Users/jff/.local/src/GraphUnzip/solve_ambiguities.py", line 601, in solve_ambiguities
    get_rid_of_bad_links(listOfSegments, interactionMatrix, tagInteractionMatrix, names, copiesNumber, stringenceReject, stringenceAccept, debugDir = debugDir, neighborsOfNeighbors = useNeighborOfNeighbor, verbose = verbose)
  File "/Users/jff/.local/src/GraphUnzip/solve_ambiguities.py", line 485, in get_rid_of_bad_links
    linksStrength = intensity_of_interactions(segment, endOfSegment, [n1,n2], listOfSegments, interactionMatrix, names, copiesnumber, debugDir = debugDir)
  File "/Users/jff/.local/src/GraphUnzip/solve_ambiguities.py", line 112, in intensity_of_interactions
    commonContigs = compute_commonContigs2(segment, endOfSegment, listOfNeighborIndices, 2000000)
  File "/Users/jff/.local/src/GraphUnzip/solve_ambiguities.py", line 156, in compute_commonContigs2
    propagate_vicinity(segment.links[endOfSegment][n], segment.otherEndOfLinks[endOfSegment][n], vicinityContigs, 0, depth)
  File "/Users/jff/.local/src/GraphUnzip/solve_ambiguities.py", line 178, in propagate_vicinity
    propagate_vicinity(neighbor, segment.otherEndOfLinks[1-endOfSegment][n], vicinityContigs, depth+segment.length , limitDepth)
  File "/Users/jff/.local/src/GraphUnzip/solve_ambiguities.py", line 178, in propagate_vicinity
    propagate_vicinity(neighbor, segment.otherEndOfLinks[1-endOfSegment][n], vicinityContigs, depth+segment.length , limitDepth)
  File "/Users/jff/.local/src/GraphUnzip/solve_ambiguities.py", line 178, in propagate_vicinity
    propagate_vicinity(neighbor, segment.otherEndOfLinks[1-endOfSegment][n], vicinityContigs, depth+segment.length , limitDepth)
  [Previous line repeated 985 more times]
  File "/Users/jff/.local/src/GraphUnzip/segment.py", line 82, in get_length
    return np.sum(self._lengths)
  File "<__array_function__ internals>", line 5, in sum
  File "/Users/jff/miniconda3/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 2259, in sum
    return _wrapreduction(a, np.add, 'sum', axis, dtype, out, keepdims=keepdims,
  File "/Users/jff/miniconda3/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 70, in _wrapreduction
    passkwargs = {k: v for k, v in kwargs.items()
RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by jflot** [comment]
I solved this problem by adding 
`import sys`
`sys.setrecursionlimit(10000)`
at the beginning of graphunzip.py

**Comment by RolandFaure** [comment]
Thank you for bringing this problem up. This problem occurs on very complex GFA with lots of short contigs. There could still be bugs with this fix on even more complex GFAs. It will be fixed more definitely very shortly.

**Comment by RolandFaure** [comment]
I fixed this problem definitively, the workaround you proposed is not needed anymore.
